### PR TITLE
Add logo to readme

### PR DESCRIPTION
**Pull request by HerbCaudill**
image

### CODE REVIEW

**Comment by HerbCaudill** [comment]
FWIW - going with the roadway signage metaphor, the font is [Interstate, by Tobias Frere-Jones](https://en.wikipedia.org/wiki/Interstate_(typeface)). 

> Interstate is based on the font colloquially known as Highway Gothic, the official typeface of the American Federal Highway Administration, designed by Ted Forbes in 1949. Forbes was an engineer not a typographer, and the letterforms in the original Highway Gothic typeface are quirky—the awkward and incongruous descender of the lowercase g is a good example. "It's very American in that way—just smash it together and get it up there," Frere-Jones has said of Highway Gothic. Interstate was carefully designed as homage to Highway Gothic, its naïveté intentional. Interstate has a familiar and recognizable feel, conveying the aesthetic of the American road and the excitement associated with the new interstate highway system of the Eisenhower era.

**Comment by ept** [comment]
I love it! I find the road sign style immediately recognisable and iconic, and it fits the project name well.

I was wondering whether we should have a more general logo competition, but then came to the conclusion that I like this design so much that I'm happy to just run with it. But I would like to have an informal community vote of sorts. So, everyone who cares, can you please vote on @HerbCaudill's initial post above, using the thumbs-up/thumbs-down emoji reactions?

A few small things. Firstly, I find the spacing between the merge symbol and the letters a bit tight. Here is a proposed tweak, with slightly adjusted spacing — what do you think?

Logo with spacing tweaked

Secondly, would we need a license to use the typeface? I have no idea how font licensing works.

Finally, could you please adjust the patch to README.md to not include unrelated reformatting of code examples? Thanks!

**Comment by ept** [comment]
Regarding licensing, it looks like a $40 [Desktop license](http://www.typenetwork.com/support) is sufficient for creating static images and print documents. I'm happy to cover that cost if you don't already have a license. And I'm looking forward to printing stickers 😄

**Comment by HerbCaudill** [comment]
I have a license via Adobe Typekit. I'll make those changes later today.

**Comment by HerbCaudill** [comment]
I've reverted the auto-formatting - sorry about that! Long story involving my prettier settings in VS Code.

I've also applied the wider spacing to all the generated assets. Here's the illustrator file in case it's ever of use to anyone. 
[automerge 1.02.ai.zip](https://github.com/automerge/automerge/files/4794821/automerge.1.02.ai.zip)

**Comment by philschatz** [comment]
I really :heart: what the logo conveys. If you are interested in an open font alternative, [Overpass](http://overpassfont.org) by RedHat keeps with the roadway signage metaphor but is [openly licensed](https://github.com/RedHatOfficial/Overpass/blob/master/LICENSE.md).

**Comment by ept** [comment]
Okay, as we seem to have general agreement, I've merged this. Thank you so much @HerbCaudill!

**Pull request merged**
