### PR TITLE
Adding Text field API to translate between usize position and Cursor

### PR DESCRIPTION
**Pull request by munhitsu**
It's implementing #535.

But it's O(N)

### CODE REVIEW

**Comment by alexjg** [comment]
I think this is something which would be useful to add. There are two things I can think of that we might want to think about:

1. The most practical concern: https://github.com/automerge/automerge/pull/572 just landed and that may require changes in this code.
2. I don't think we should use the `ExId` for the "address". Instead i think we should introduce an `ExElemId` type (for "external element ID"). Internally we use `crate::types::ElemId` to refer to elements in a sequence. This is different to an object ID in that the "zero" element always refers to the start of the sequence whereas the zero of `ExId` is the Root object. It's also a bit clearer to have a different type for elements of a sequence vs object IDs.

**Comment by orionz** [comment]
Thanks for this.  I wanted to add a lot so you should find a PR for your PR! ;)

**Comment by munhitsu** [comment]
@orionz thanks for awesome contribution. Now it's a nice cheap O(log(n)). Can't wait to use it.
@alexjg comments addressed

**Comment by alexjg** [comment]
This looks great. The only remaining thing is that we need some docs on the new `ReadDoc` methods and on the `Cursor` type describing what this is for.

**Comment by munhitsu** [comment]
I've just added some light touch docs

**Pull request merged**
