### PR TITLE
Rename crate::exid::ExId to crate::obj_id::ObjId

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by teohhanhui** [comment]
> Now, the interesting question is whether this has any compatibility effects. It seems like it should definitely not, because the exported name and type have not changed, but I am cautious.

If we used type alias it'd have compatibility concerns: https://predr.ag/blog/re-exporting-enum-with-type-alias-breaking-change-not-major/

But we didn't. There are no compatibility concerns that I'm aware of.

> @teohhanhui did you encounter anywhere when you wrote code against this library that had to use `ExId` rather than `ObjId`?

No.

**Comment by alexjg** [comment]
> This change doesn't fix everything. Wherever ExId is still present in impl block header or function / method signature...

Can you elaborate?

**Comment by teohhanhui** [comment]
e.g.

https://github.com/automerge/automerge/blob/9400e195f1d01b0c10d535c1c1ccd321e684c362/rust/automerge/src/autocommit.rs#L574

results in

Screenshot 2023-10-04 at 23-51-40 AutoCommit in automerge - Rust

**Comment by teohhanhui** [comment]
Looks like that will be fixed soon: https://github.com/rust-lang/rust/pull/113374

**Comment by alexjg** [comment]
Hmm, do we need to make this change then?

**Comment by teohhanhui** [comment]
In the linked PR, I don't see any tests for `impl` block header.

**Comment by teohhanhui** [comment]
Looks like that's https://github.com/rust-lang/rust/issues/41072

**Comment by alexjg** [comment]
I'm inclined to think that this is a rustdoc bug and we should just wait for it to be fixed as even with these changes we end up with `ExId` leaking out, wdyt?

**Pull request closed without merging**
