### PR TITLE
fix README.md bug and fix the Duplicate declaration "diff"

### PR DESCRIPTION
**Pull request by yi-ge**
```
  let diffs = [], diff
  for (let change of changes) {
    [opSet, diff] = OpSet.addChange(opSet, change)
    diffs.push(...diff)
  }
```

The diff had duplicate declaration.

If not fix this bug, it will cause webpack to compile exceptions.

### CODE REVIEW

**Comment by ept** [comment]
Hi @yi-ge, thanks for your PR. I've merged in the README update 3a2786ab3774e22ff322700917e7c0bcf443e93c. However, I disagree about the duplicate declaration of "diff": the variable is only being declared once in that function. In what context were you getting an error?

**Comment by j-f1** [comment]
It looks like the local `diff` variable isn’t declared there. What do you think about changing that section to this?

```js
for (let change of changes) {
  let [newOpSet, diff] = OpSet.addChange(opSet, change)
  diffs.push(...diff)
  opSet = newOpSet
}
```

**Comment by ept** [comment]
That would work too, but I don't see anything wrong with the original code, and I can't reproduce the exception with webpack.

**Comment by yi-ge** [comment]
@ept @j-f1 If not remove `diff`, webpack will show error `Duplicate declaration "diff"` in my terminal. In `[newOpSet, diff]`, `diff` is an array destructuring.

**Comment by yi-ge** [comment]
wechatimg104

@ept @j-f1 My colleagues build in electron.

**Comment by ept** [comment]
Strange — that must be a bug in the version of webpack you're using. With webpack 3.11.0 I don't get this error.

Anyhow, I've updated the code as suggested by @j-f1 in 2e5af0185b9baa920c880c71c1691f1c91a9520c. Could you please give it a try and see whether it works now?

**Comment by yi-ge** [comment]
@ept Thank you. It work well now.

**Pull request closed without merging**
